# Human-readable mod name, available for mcmod.info population.
modName = MTN Example

# Case-sensitive identifier string, available for mcmod.info population.
# Conventionally lowercase.
modId = mtnexample

# Root package of the mod, used to find various classes in other properties
# and for mcmod.info substitution.
modGroup = com.mtn.example

# Version of Minecraft to target
minecraftVersion = 1.7.10

# Version of Minecraft Forge to target
forgeVersion = 10.13.4.1614

# MCP mappings used for dependency deobfuscation.
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# Default username for testing (runClient/runServer). Can be overridden per-run.
developmentEnvironmentUserName = Developer
